import { type Category, type MarketplaceProduct } from "@/lib/pixelshelf-data";
import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type Locale = "en" | "ru";

const copy = {
  en: {
    games: "Games",
    currencyPacks: "Currency packs",
    howItWorks: "How it works",
    searchCurrencyPacks: "Search currency packs",
    themeLight: "Light theme",
    themeDark: "Dark theme",
    currencyLabel: "Display currency",
    savedBundles: "Saved bundles",
    saveBundle: "Save bundle",
    removeSavedBundle: "Remove from saved",
    showSaved: "Show saved",
    showAllPacks: "Show all packs",
    noSavedBundles: "No saved bundles yet.",
    noSavedBundlesCopy: "Save a currency bundle to compare it later.",
    searchSuggestions: "Search suggestions",
    suggestionBundle: "Bundle",
    suggestionGame: "Game",
    suggestionCurrency: "Currency",
    noSuggestions: "No matching currencies or bundles.",
    heroEyebrow: "Virtual currency, ready for the next run",
    heroHeading: "Power up your",
    heroAccent: "next play.",
    heroDescription: "Browse original game-currency packs with clear bonus values, instant local cart updates, and a streamlined top-up flow.",
    searchGames: "Search games, currencies, or bundles",
    search: "Search",
    browseCurrencyPacks: "Browse currency packs",
    heroArtLabel: "PixelGame / Game Vault",
    heroArtTitle: "More play, ready when you are.",
    freshDrops: "Fresh drops",
    catalogHeading: "Choose your world. Stack your currency.",
    catalogDescription: "Compare curated local currency bundles across a set of fictional game worlds.",
    allGames: "All games",
    allPackTypes: "All",
    packType: "Pack type",
    packs: "packs",
    viewBundle: "View bundle",
    noPacks: "No packs matched your search.",
    noPacksCopy: "Try a different game, currency, or pack type.",
    priceRange: "Price range",
    allPrices: "All prices",
    budgetPrice: "$10 and under",
    standardPrice: "$11–20",
    premiumPrice: "$21 and above",
    sortBy: "Sort by",
    featuredSort: "Featured",
    lowToHigh: "Price: low to high",
    highToLow: "Price: high to low",
    resetFilters: "Reset controls",
    featuredWorlds: "Featured worlds",
    featuredHeading: "Find the game you want to power up.",
    nextRun: "Ready for the next run",
    closingHeading: "Pick a bundle. Power your play.",
    exploreAllPacks: "Explore all packs",
    footer: "Made for ideas in motion.",
    cart: "Cart",
    yourTopUp: "Your top-up",
    topUpRequestComplete: "Top-up request complete",
    topUpCompleteCopy: "This local preview cleared your cart. Connect the action to an approved virtual-currency checkout when your live catalog is ready.",
    keepBrowsing: "Keep browsing",
    queueClear: "Your queue is clear",
    queueCopy: "Add a currency pack and it will stay here while you browse.",
    explorePacks: "Explore packs",
    subtotal: "Subtotal",
    cartNote: "Local preview checkout. Connect only approved virtual-item checkout and fulfillment after your catalog is ready.",
    continueTopUp: "Continue to top-up",
    closeCart: "Close cart",
    decrease: "Decrease quantity",
    increase: "Increase quantity",
    remove: "Remove",
    backToCatalog: "Back to catalog",
    preview: "Digital asset preview",
    virtualCurrencyBundle: "virtual currency bundle",
    instantDownload: "Instant download",
    addToTopUp: "Add to top-up",
    included: "What’s included",
    detailNote: "A local top-up flow is active for this preview. Connect approved virtual-item checkout and fulfillment only after your real catalog is ready.",
    missingTitle: "That pack has moved out of the vault.",
    browseVault: "Browse PixelGame",
    account: "Account",
    accountEyebrow: "Local buyer profile",
    accountTitle: "Your PixelGame account",
    accountDescription: "Track your simulated currency orders and keep the bundles you saved for a later top-up.",
    ordersCount: "orders",
    inCartCount: "in cart",
    savedCount: "saved",
    pendingCart: "Cart awaiting checkout",
    pendingCartDescription: "These bundles are reserved locally in your cart. Confirm the simulated payment to move them into order history.",
    continueCheckout: "Continue to checkout",
    orderHistoryEyebrow: "Purchase history",
    orderHistory: "Order history",
    noOrders: "No orders yet",
    noOrdersCopy: "Complete a local checkout to see your virtual currency delivery history here.",
    paidSimulated: "Paid · simulated",
    savedForLaterEyebrow: "Your shortlist",
    savedForLater: "Saved for later",
    checkoutEyebrow: "Secure local preview",
    checkoutTitle: "Complete your top-up",
    checkoutDescription: "Review your game-currency selection and confirm a simulated payment. No real payment information is collected.",
    checkoutDemo: "Demo checkout only — this page simulates a successful payment and local delivery record.",
    billingEmail: "Email for the delivery preview",
    playerTag: "Player tag",
    simulatedPayment: "Simulated payment",
    simulatedPaymentCopy: "No card or wallet is charged in this preview.",
    payDemo: "Confirm simulated payment",
    orderSummary: "Order summary",
    checkoutEmpty: "Your checkout is ready when you are",
    checkoutEmptyCopy: "Add a currency bundle to the cart before starting a simulated payment.",
    paymentSuccessEyebrow: "Top-up confirmed",
    paymentSuccess: "Simulated payment successful",
    paymentSuccessCopy: "Your local order record is saved. The virtual currency is marked for preview delivery — no real charge was made.",
    processingPayment: "Processing simulated payment…",
    repeatOrder: "Repeat order",
    orderNumber: "Order number",
    viewAccount: "View account",
    signInEyebrow: "Secure sign-in",
    signInTitle: "Connect your buyer profile",
    signInDescription: "Use a supported identity provider for a protected buyer session. Your local simulated orders and saved bundles remain in this browser.",
    continueWithGoogle: "Continue with Google",
    continueWithSteam: "Continue with Steam",
    steamId: "Steam ID",
    signedInAs: "Signed in as",
    signOut: "Sign out",
    secureProvider: "Protected by a dedicated OAuth backend",
    providerPreparing: "Secure provider setup in progress",
    steamProvider: "Steam",
    appleProvider: "Apple ID",
    telegramProvider: "Telegram",
  },
  ru: {
    games: "Игры",
    currencyPacks: "Валютные наборы",
    howItWorks: "Как это работает",
    searchCurrencyPacks: "Поиск валютных наборов",
    themeLight: "Светлая тема",
    themeDark: "Тёмная тема",
    currencyLabel: "Валюта отображения",
    savedBundles: "Сохранённые наборы",
    saveBundle: "Сохранить набор",
    removeSavedBundle: "Убрать из сохранённых",
    showSaved: "Показать сохранённые",
    showAllPacks: "Показать все наборы",
    noSavedBundles: "Сохранённых наборов пока нет.",
    noSavedBundlesCopy: "Сохраните валютный набор, чтобы сравнить его позже.",
    searchSuggestions: "Подсказки поиска",
    suggestionBundle: "Набор",
    suggestionGame: "Игра",
    suggestionCurrency: "Валюта",
    noSuggestions: "Подходящих валют или наборов не найдено.",
    heroEyebrow: "Игровая валюта для следующего забега",
    heroHeading: "Усильте свою",
    heroAccent: "следующую игру.",
    heroDescription: "Выбирайте оригинальные наборы игровой валюты с понятными бонусами, мгновенным обновлением локальной корзины и простым потоком пополнения.",
    searchGames: "Поиск игр, валюты или наборов",
    search: "Найти",
    browseCurrencyPacks: "Смотреть валютные наборы",
    heroArtLabel: "PixelGame / Игровое хранилище",
    heroArtTitle: "Больше игры — когда вы готовы.",
    freshDrops: "Новые поступления",
    catalogHeading: "Выберите мир. Пополните валюту.",
    catalogDescription: "Сравнивайте локальные демонстрационные наборы валюты из вымышленных игровых миров.",
    allGames: "Все игры",
    allPackTypes: "Все",
    packType: "Тип набора",
    packs: "наборов",
    viewBundle: "Открыть набор",
    noPacks: "По вашему запросу наборов не найдено.",
    noPacksCopy: "Попробуйте другую игру, валюту или тип набора.",
    priceRange: "Диапазон цен",
    allPrices: "Все цены",
    budgetPrice: "До $10",
    standardPrice: "$11–20",
    premiumPrice: "$21 и выше",
    sortBy: "Сортировка",
    featuredSort: "Рекомендуемые",
    lowToHigh: "Цена: по возрастанию",
    highToLow: "Цена: по убыванию",
    resetFilters: "Сбросить параметры",
    featuredWorlds: "Избранные миры",
    featuredHeading: "Найдите игру, которую хотите усилить.",
    nextRun: "Готово к следующему забегу",
    closingHeading: "Выберите набор. Усильте игру.",
    exploreAllPacks: "Все наборы",
    footer: "Создано для идей в движении.",
    cart: "Корзина",
    yourTopUp: "Ваше пополнение",
    topUpRequestComplete: "Заявка на пополнение оформлена",
    topUpCompleteCopy: "В локальном предварительном просмотре корзина очищена. Подключите проверенный платёжный поток для игровой валюты, когда живой каталог будет готов.",
    keepBrowsing: "Продолжить просмотр",
    queueClear: "Ваша очередь пуста",
    queueCopy: "Добавьте валютный набор — он сохранится здесь, пока вы продолжаете просмотр.",
    explorePacks: "Смотреть наборы",
    subtotal: "Подытог",
    cartNote: "Локальный демонстрационный checkout. Подключайте одобренную оплату и выдачу виртуальных товаров после подготовки каталога.",
    continueTopUp: "Перейти к пополнению",
    closeCart: "Закрыть корзину",
    decrease: "Уменьшить количество",
    increase: "Увеличить количество",
    remove: "Удалить",
    backToCatalog: "Вернуться к каталогу",
    preview: "Предпросмотр цифрового товара",
    virtualCurrencyBundle: "набор игровой валюты",
    instantDownload: "Мгновенное получение",
    addToTopUp: "Добавить к пополнению",
    included: "Что входит в набор",
    detailNote: "В этом предварительном просмотре включён локальный поток пополнения. Подключите одобренную оплату и выдачу виртуальных товаров после подготовки реального каталога.",
    missingTitle: "Этот набор больше не доступен в хранилище.",
    browseVault: "Открыть PixelGame",
    account: "Кабинет",
    accountEyebrow: "Локальный профиль покупателя",
    accountTitle: "Ваш кабинет PixelGame",
    accountDescription: "Просматривайте демонстрационные заказы игровой валюты и сохранённые наборы для будущего пополнения.",
    ordersCount: "заказов",
    inCartCount: "в корзине",
    savedCount: "сохранено",
    pendingCart: "Корзина ожидает оформления",
    pendingCartDescription: "Эти наборы сохранены локально в корзине. Подтвердите симулированную оплату, чтобы они появились в истории заказов.",
    continueCheckout: "Перейти к checkout",
    orderHistoryEyebrow: "История покупок",
    orderHistory: "История заказов",
    noOrders: "Заказов пока нет",
    noOrdersCopy: "Оформите локальный checkout, и история виртуальной выдачи появится здесь.",
    paidSimulated: "Оплачено · симуляция",
    savedForLaterEyebrow: "Ваш список",
    savedForLater: "Сохранено на потом",
    checkoutEyebrow: "Безопасный локальный просмотр",
    checkoutTitle: "Завершите пополнение",
    checkoutDescription: "Проверьте выбранную игровую валюту и подтвердите симулированную оплату. Реальные платёжные данные не запрашиваются.",
    checkoutDemo: "Только демонстрационный checkout — страница имитирует успешную оплату и сохраняет локальный заказ.",
    billingEmail: "Email для демонстрации выдачи",
    playerTag: "Игровой тег",
    simulatedPayment: "Симулированная оплата",
    simulatedPaymentCopy: "В этом предварительном просмотре карта или кошелёк не списываются.",
    payDemo: "Подтвердить симулированную оплату",
    orderSummary: "Состав заказа",
    checkoutEmpty: "Checkout будет готов, когда вы выберете набор",
    checkoutEmptyCopy: "Добавьте валютный набор в корзину перед началом симулированной оплаты.",
    paymentSuccessEyebrow: "Пополнение подтверждено",
    paymentSuccess: "Симулированная оплата прошла успешно",
    paymentSuccessCopy: "Локальная запись заказа сохранена. Виртуальная валюта отмечена для демонстрационной выдачи — реального списания не было.",
    processingPayment: "Обрабатываем симулированную оплату…",
    repeatOrder: "Повторить заказ",
    orderNumber: "Номер заказа",
    viewAccount: "Открыть кабинет",
    signInEyebrow: "Безопасный вход",
    signInTitle: "Подключите профиль покупателя",
    signInDescription: "Используйте поддерживаемый провайдер для защищённой сессии покупателя. Локальные демонстрационные заказы и сохранённые наборы остаются в этом браузере.",
    continueWithGoogle: "Продолжить с Google",
    continueWithSteam: "Продолжить со Steam",
    steamId: "Steam ID",
    signedInAs: "Вы вошли как",
    signOut: "Выйти",
    secureProvider: "Защищено отдельным OAuth-backend",
    providerPreparing: "Безопасная настройка провайдера продолжается",
    steamProvider: "Steam",
    appleProvider: "Apple ID",
    telegramProvider: "Telegram",
  },
} as const;

const russianProductCopy: Record<string, Partial<Pick<MarketplaceProduct, "title" | "description" | "longDescription" | "bundleLabel" | "delivery" | "includes">>> = {
  "product-nova-explorer": {
    title: "Набор исследователя",
    description: "Стартовое пополнение для следующей экспедиции.",
    longDescription: "Начните новый забег с практичным запасом Nova Credits для вымышленного аккаунта NovaVerse. Локальный предварительный просмотр демонстрирует прозрачный набор, цену и процесс получения до подключения реального коммерческого каталога.",
    bundleLabel: "1 200 + 120 бонус",
    delivery: "Цифровая выдача кредитов",
    includes: ["1 200 Nova Credits", "120 бонусных кредитов", "Предпросмотр цифровой выдачи"],
  },
  "product-nova-vanguard": {
    title: "Хранилище авангарда",
    description: "Выгодный запас кредитов для долгих миссий.",
    longDescription: "Хранилище авангарда — это увеличенный вымышленный набор Nova Credits с понятным указанием бонуса и простым переходом к виртуальной выдаче. Он создан для игроков, которым нужен один заметный вариант пополнения.",
    bundleLabel: "4 000 + 600 бонус",
    delivery: "Цифровая выдача кредитов",
    includes: ["4 000 Nova Credits", "600 бонусных кредитов", "Предпросмотр цифровой выдачи"],
  },
  "product-aether-trailblazer": {
    title: "Кошель первопроходца",
    description: "Компактный набор Aether Coins для следующего задания.",
    longDescription: "Кошель первопроходца — это вымышленный набор валюты Arcane Realms с легко считываемой ценностью. Локальный поток делает количество, бонус, цену и ожидания по виртуальной выдаче понятными до checkout.",
    bundleLabel: "850 + 85 бонус",
    delivery: "Цифровая выдача монет",
    includes: ["850 Aether Coins", "85 бонусных монет", "Предпросмотр цифровой выдачи"],
  },
  "product-aether-royal": {
    title: "Королевская казна",
    description: "Королевский запас монет с бонусом к ценности.",
    longDescription: "Королевская казна — это вымышленный набор монет Arcane Realms для более крупных демонстраций пополнения. В предложении точно показано наполнение, а покупатель проходит через тот же понятный поток корзины.",
    bundleLabel: "3 500 + 525 бонус",
    delivery: "Цифровая выдача монет",
    includes: ["3 500 Aether Coins", "525 бонусных монет", "Предпросмотр цифровой выдачи"],
  },
  "product-pulse-matchday": {
    title: "Набор матча",
    description: "Яркий запас Pulse Tokens для ежедневной игры.",
    longDescription: "Набор матча представляет вымышленный комплект токенов Neon Circuit в динамичном игровом оформлении. В нём легко сравнить основное количество токенов, бонус и указанную цену.",
    bundleLabel: "1 500 + 150 бонус",
    delivery: "Цифровая выдача токенов",
    includes: ["1 500 Pulse Tokens", "150 бонусных токенов", "Предпросмотр цифровой выдачи"],
  },
  "product-pulse-champion": {
    title: "Набор чемпиона",
    description: "Выгодный набор токенов для полного игрового сезона.",
    longDescription: "Набор чемпиона — это вымышленный вариант пополнения Neon Circuit с сильной премиальной ценностью. Он сохраняет локальную корзину и демонстрацию checkout, подчёркивая контекст виртуальной выдачи.",
    bundleLabel: "5 000 + 1 000 бонус",
    delivery: "Цифровая выдача токенов",
    includes: ["5 000 Pulse Tokens", "1 000 бонусных токенов", "Предпросмотр цифровой выдачи"],
  },
};

const russianCategoryCopy: Record<Category, string> = {
  Templates: "Шаблоны",
  "Design Resources": "Дизайн-ресурсы",
  "Business Tools": "Бизнес-инструменты",
};

const russianCreatorRoles: Record<string, string> = {
  "Sci-fi frontier": "Научно-фантастический мир",
  "Fantasy adventure": "Фэнтезийное приключение",
  "Competitive arcade": "Соревновательный аркадный мир",
  "Open-world RPG": "Ролевая игра с открытым миром",
};

type LanguageContextValue = {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (typeof copy)[Locale];
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function getLocalizedProduct(product: MarketplaceProduct, locale: Locale): MarketplaceProduct {
  return locale === "ru" ? { ...product, ...russianProductCopy[product.id] } : product;
}

export function getLocalizedCategory(category: Category, locale: Locale) {
  return locale === "ru" ? russianCategoryCopy[category] : category;
}

export function getLocalizedCreatorRole(role: string, locale: Locale) {
  return locale === "ru" ? russianCreatorRoles[role] ?? role : role;
}

export function resolveInitialLocale(storedLocale: string | null, search: string): Locale {
  const requestedLocale = new URLSearchParams(search).get("lang");
  if (requestedLocale === "ru" || requestedLocale === "en") return requestedLocale;
  return storedLocale === "ru" ? "ru" : "en";
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>(() => {
    if (typeof window === "undefined") return "en";
    return resolveInitialLocale(window.localStorage.getItem("pixelshelf:locale"), window.location.search);
  });

  useEffect(() => {
    window.localStorage.setItem("pixelshelf:locale", locale);
    document.documentElement.lang = locale;
  }, [locale]);

  const value = useMemo(() => ({ locale, setLocale, t: copy[locale] }), [locale]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
